export const doctorFormData = {
  id: "",
  Doctor_name: "",
  Doctor_degree: "",
  Doctor_experience: "",
  Doctor_speciality: "",
  Profile_image: null,
  Contact_no: "",
  Alternate_contact: "",
  Whatsapp_no: "",
  Email_id: "",
  Doctor_fees: "",
  Address: "",
  City: "",
  Country: "",
  Region: "",
  Password: "",
  status: "",
  Approval_status: "",
  Created_by: "",
  Updated_by: "",
  Approved_by: "",
};
