export const doctorFormData = [
  {
    Doctor_name: "",
    Doctor_degree: "",
    Doctor_experience: "",
    Doctor_speciality: "",
    Profile_image: null,
    Contact_no: "",
    Alternate_contact: "",
    Whatsapp_no: "",
    Email_id: "",
    Address: "",
    Country: "",
    Region: "",
    Password: "",
    status: "",
    Approval_status: "",
    Created_by: "",
    Updated_by: "",
    Approved_by: "",
    approved_date: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const DoctorFields = [
  {
    label: "Doctor Name",
    type: "text",
    id: "doctor-name",
    name: "doctor-name",
    placeHolder: "Enter Doctor Name",
    layout: "col",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Doctor Degree",
    type: "text",
    id: "Doctor_degree",
    name: "Doctor_degree",
    placeHolder: "Enter Your degree",
    layout: "col",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Doctor Experience",
    type: "number",
    id: "Doctor_experience",
    name: "Doctor_experience",
    layout: "col",
    placeHolder: "how experience have you?",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Doctor Specility",
    type: "text",
    id: "Doctor_speciality",
    name: "Doctor_speciality",
    placeHolder: "You Expert in ",
    layout: "col",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Your Profile",
    type: "file",
    id: "Profile_image",
    name: "Profile_image",
    layout: "col",
    placeHolder: "Your Profile Pic",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Contact Number",
    type: "text",
    id: "Contact_no",
    name: "Contact_no",
    layout: "col",
    placeHolder: "You Expert in ",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Alternate contact",
    type: "text",
    id: "Alternate_contact",
    name: "Alternate_contact",
    layout: "col",
    placeHolder: "Alternate contact",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Whatsapp number",
    type: "text",
    id: "Whatsapp_no",
    name: "Whatsapp_no",
    placeHolder: "Whatsapp no",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Email Id",
    type: "email",
    id: "Email_id",
    name: "Email_id",
    placeHolder: "Your working Email",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Password",
    type: "text",
    id: "Password",
    name: "Password",
    placeHolder: " Create your Password",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Address",
    type: "text",
    id: "Address",
    name: "Address",
    placeHolder: "Address",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Country",
    type: "text",
    id: "Country",
    name: "Country",
    placeHolder: " choose your Country",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Region",
    type: "text",
    id: "Region",
    name: "Region",
    placeHolder: " choose your Region",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Created_by",
    type: "text",
    id: "Created_by",
    name: "Created_by",
    placeHolder: "  Created_by",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "Approved_by",
    type: "text",
    id: "Approved_by",
    name: "Approved_by",
    placeHolder: "  Approved_by",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
  {
    label: "approved_date",
    type: "date",
    id: "approved_date",
    name: "approved_date",
    placeHolder: "  approved_date",
    className: "py-2 px-3 rounded-full bg-gray-50 text-primary",
  },
];
