export const doctorFormData = {
  id: "",
  Doctor_name: "",
  Doctor_degree: "",
  Doctor_experience: "",
  Doctor_speciality: "",
  Profile_image: null,
  Contact_no: "",
  Alternate_contact: "",
  Whatsapp_no: "",
  Email_id: "",
  Doctor_fees: "",
  Address: "",
  City: "",
  Country: "",
  Region: "",
  Password: "",
  status: "",
  Approval_status: "",
  Created_by: "",
  Updated_by: "",
  Approved_by: "",
};

export const hospitalFields = {
  id: "",
  H_image: "",
  H_name: "",
  H_category: "",
  H_short_add: "",
  H_full_add: "",
  H_contact_no: "",
  H_advance_Appointment: true,
  H_Todays_Appointment: false,
  H_email_id: "",
  H_password: "",
  Amenities: "",
  Description: "",
  status: "",
  Approval_status: "",
  Created_by: "",
  Updated_by: "",
  Approved_by: "",
};

export const appointmentfields = {
  id: "",
  patient_id: "",
  hospital_id: "",
  doctor_id: "",
  Appointment_type: "",
  Appointment_req: "",
  Status: "",
  appointment_scheduled_date: "",
  token_number: "",
  Created_by: "",
  Updated_by: "",
  Approved_by: "",
  Approved_date: "",
  createdAt: "",
  updatedAt: "",
};

export const patients = {
  id: "",
  user_email: "",
  user_password: "",
  first_name: "",
  middle_name: "",
  last_name: "",
  gender: "",
  dob: "",
  contact: "",
  alt_contact: "",
  recovery_email: "",
  address: "",
  country: "",
  city: "",
  status: "",
  created_by: "",
  updated_by: "",
  approved_by: "",
  approved_date: "",
};
